player(a).
playerLocation(1,7).
health(100).
hunger(96).
thirst(98).
weapon(none).
totalEnemy(11).
inventory(rencong).
inventory(radar).
objectAt(10,13,weapon,celurit).
objectAt(10,15,weapon,keris).
objectAt(10,16,weapon,kujang).
objectAt(4,13,weapon,badik).
objectAt(4,2,weapon,rencong).
objectAt(14,5,medicine,jahe).
objectAt(12,3,medicine,temulawak).
objectAt(9,4,medicine,kumiskucing).
objectAt(2,8,medicine,lidahbuaya).
objectAt(4,16,medicine,cincau).
objectAt(3,19,food,pempek).
objectAt(3,1,food,martabak).
objectAt(6,6,food,rendang).
objectAt(11,15,food,sotomedan).
objectAt(10,6,food,mieaceh).
objectAt(6,6,weapon,celurit).
objectAt(14,19,weapon,keris).
objectAt(2,8,weapon,kujang).
objectAt(3,5,weapon,badik).
objectAt(11,12,weapon,rencong).
objectAt(2,2,medicine,jahe).
objectAt(10,16,medicine,temulawak).
objectAt(3,16,medicine,kumiskucing).
objectAt(10,13,medicine,lidahbuaya).
objectAt(5,8,medicine,cincau).
objectAt(11,14,food,pempek).
objectAt(1,1,food,martabak).
objectAt(9,12,food,rendang).
objectAt(14,3,food,sotomedan).
objectAt(6,5,food,mieaceh).
objectAt(7,16,weapon,celurit).
objectAt(13,9,weapon,keris).
objectAt(5,10,weapon,kujang).
objectAt(4,9,weapon,badik).
objectAt(7,19,weapon,rencong).
objectAt(8,3,medicine,jahe).
objectAt(13,17,medicine,temulawak).
objectAt(3,18,medicine,kumiskucing).
objectAt(10,13,medicine,lidahbuaya).
objectAt(10,10,medicine,cincau).
objectAt(7,2,food,pempek).
objectAt(13,10,food,martabak).
objectAt(11,1,food,rendang).
objectAt(12,14,food,sotomedan).
objectAt(13,14,food,mieaceh).
objectAt(7,14,weapon,celurit).
objectAt(9,17,weapon,keris).
objectAt(2,8,weapon,kujang).
objectAt(8,10,weapon,badik).
objectAt(12,6,weapon,rencong).
objectAt(14,19,medicine,jahe).
objectAt(10,14,medicine,temulawak).
objectAt(7,16,medicine,kumiskucing).
objectAt(14,13,medicine,lidahbuaya).
objectAt(11,9,medicine,cincau).
objectAt(9,16,food,pempek).
objectAt(7,10,food,martabak).
objectAt(4,17,food,rendang).
objectAt(10,18,food,sotomedan).
objectAt(10,5,food,mieaceh).
objectAt(12,18,weapon,celurit).
objectAt(5,9,weapon,keris).
objectAt(11,9,weapon,kujang).
objectAt(4,3,weapon,badik).
objectAt(2,4,medicine,jahe).
objectAt(2,17,medicine,temulawak).
objectAt(14,8,medicine,kumiskucing).
objectAt(6,3,medicine,lidahbuaya).
objectAt(1,18,medicine,cincau).
objectAt(6,4,food,pempek).
objectAt(4,10,food,martabak).
objectAt(9,16,food,rendang).
objectAt(2,13,food,sotomedan).
objectAt(5,12,food,mieaceh).
objectAt(2,4,weapon,celurit).
objectAt(7,19,weapon,keris).
objectAt(4,10,weapon,kujang).
objectAt(2,11,weapon,badik).
objectAt(14,8,weapon,rencong).
objectAt(8,3,medicine,jahe).
objectAt(9,19,medicine,temulawak).
objectAt(9,17,medicine,kumiskucing).
objectAt(7,3,medicine,lidahbuaya).
objectAt(6,8,medicine,cincau).
objectAt(3,13,food,pempek).
objectAt(13,13,food,martabak).
objectAt(3,7,food,rendang).
objectAt(14,5,food,sotomedan).
objectAt(1,14,food,mieaceh).
objectAt(1,8,weapon,celurit).
objectAt(2,6,weapon,keris).
objectAt(11,3,weapon,kujang).
objectAt(3,5,weapon,badik).
objectAt(9,16,weapon,rencong).
objectAt(8,17,medicine,jahe).
objectAt(14,15,medicine,temulawak).
objectAt(8,10,medicine,kumiskucing).
objectAt(12,1,medicine,lidahbuaya).
objectAt(3,11,medicine,cincau).
objectAt(5,4,food,pempek).
objectAt(8,9,food,martabak).
objectAt(4,8,food,rendang).
objectAt(6,16,food,sotomedan).
objectAt(9,17,food,mieaceh).
objectAt(5,10,weapon,celurit).
objectAt(4,6,weapon,keris).
objectAt(14,17,weapon,kujang).
objectAt(11,14,weapon,badik).
objectAt(13,12,weapon,rencong).
objectAt(1,14,medicine,jahe).
objectAt(12,3,medicine,temulawak).
objectAt(11,15,medicine,kumiskucing).
objectAt(14,1,medicine,lidahbuaya).
objectAt(8,9,medicine,cincau).
objectAt(4,18,food,pempek).
objectAt(8,8,food,martabak).
objectAt(14,2,food,rendang).
objectAt(4,2,food,sotomedan).
objectAt(14,10,food,mieaceh).
objectAt(8,7,weapon,celurit).
objectAt(13,10,weapon,keris).
objectAt(13,2,weapon,kujang).
objectAt(7,18,weapon,badik).
objectAt(6,4,weapon,rencong).
objectAt(4,6,medicine,jahe).
objectAt(11,10,medicine,temulawak).
objectAt(4,9,medicine,kumiskucing).
objectAt(9,17,medicine,lidahbuaya).
objectAt(10,2,medicine,cincau).
objectAt(11,15,food,pempek).
objectAt(4,19,food,martabak).
objectAt(14,7,food,rendang).
objectAt(9,15,food,sotomedan).
objectAt(11,7,food,mieaceh).
objectAt(4,1,weapon,celurit).
objectAt(13,15,weapon,keris).
objectAt(6,14,weapon,kujang).
objectAt(2,13,weapon,badik).
objectAt(12,11,weapon,rencong).
objectAt(9,18,medicine,jahe).
objectAt(6,14,medicine,temulawak).
objectAt(6,2,medicine,kumiskucing).
objectAt(10,1,medicine,lidahbuaya).
objectAt(1,11,medicine,cincau).
objectAt(12,1,food,pempek).
objectAt(6,10,food,martabak).
objectAt(10,18,food,rendang).
objectAt(1,13,food,sotomedan).
objectAt(8,5,food,mieaceh).
objectAt(11,9,radar,radar).
enemyAt(11,9,2).
enemyAt(7,17,4).
enemyAt(6,13,6).
enemyAt(10,12,7).
enemyAt(13,10,8).
enemyAt(9,2,9).
enemyAt(2,13,11).
enemyAt(2,11,1).
enemyAt(13,10,3).
enemyAt(4,6,10).
enemyAt(4,5,5).
